/-
Copyright (c) 2026 Dhruv Gupta. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dhruv Gupta
-/
import FLT_Proofs.Complexity.IndependentVC.Monotone
import FLT_Proofs.Complexity.IndependentVC.ShatterCount
import FLT_Proofs.Complexity.IndependentVC.VCFinite
import FLT_Proofs.Complexity.IndependentVC.Pullback
import FLT_Proofs.Complexity.IndependentVC.PullbackEquiv
import FLT_Proofs.Complexity.IndependentVC.Relabel
import FLT_Proofs.Complexity.IndependentVC.BooleanComb
import FLT_Proofs.Complexity.IndependentVC.BooleanCombFinite
import FLT_Proofs.Complexity.IndependentVC.UnionFinite
import FLT_Proofs.Complexity.IndependentVC.UnionTight
import FLT_Proofs.Complexity.IndependentVC.LatticeClosure
import FLT_Proofs.Complexity.IndependentVC.Dual
import FLT_Proofs.Complexity.IndependentVC.DualBound
import FLT_Proofs.Complexity.IndependentVC.VCDensity
import FLT_Proofs.Complexity.IndependentVC.MatroidStructure
import FLT_Proofs.Complexity.IndependentVC.OpenRouteR1
import FLT_Proofs.Complexity.IndependentVC.FundamentalTheorem
import FLT_Proofs.Bridge

/-!
# The framework root — one concept class under the measurement quartet

This module is the **organizing root** of the independent VC-dimension development. It does not
manufacture new theory; it makes the *discovered grammar* a consumable Lean object by collecting,
under one roof and one naming scheme, the load-bearing theorems that the three reading-axes of the
theory (structure, expressivity, capacity) all turn out to share.

The discovery (recorded in the noological synthesis at
`design-lab/learning-theory/flt_discovery_urs/noological_synthesis.md`) is that those three axes are
three coordinate charts on **one** object: a concept class `C : ConceptClass X Bool`, generated by a
single primitive — `Shatters X C S` — and organized by a four-part *measurement quartet*:

* **GR1 — the shattering generator.** `Shatters` is the one primitive; everything downstream is a
  functional of where it holds.
* **Coh (GR4) — the carrier identity.** A concept class *is* a set family *is* a binary matrix; the
  three charts speak about the same object (`bridge_round_trip`).
* **Inv (GR3) — the finite-vs-`⊤` invariant.** The only chart-independent invariant is the dichotomy
  `VCDim C < ⊤` versus `VCDim C = ⊤`; it *is* the fundamental theorem of statistical learning
  (`vcDim_fundamental_theorem`).
* **Pl (GR5) — the duality / pullback geometry.** Pullback is a contravariant functor and the dual
  is an involution-up-to-bidual; this is the plausibility-of-structure grammar.
* **Comp (GR6) — the composition calculus.** Union / intersection / Boolean combination, with
  *additivity forbidden* (the matroid Pl-kill `vcDim_not_polymatroid_rank`) and a subadditive
  surrogate one scale down at VC *density* (`hasPolyDegree_booleanComb`).

Acting on this object are **seven uniform moves** (`GM1`–`GM7`), catalogued in §"GM actions" below.

## What this module is, honestly

Almost everything here is a **re-export** (`describe`): each `framework_*` name is *definitionally*
an existing kernel theorem, surfaced under a quartet-oriented name with a docstring that points back
to its anchor. These re-exports are **not** new theorems and are not claimed as such — they are an
organizing index, the price of admission for talking about "the framework root" as one object.

The single piece of genuinely-new content is `vcDim_finite_ideal_closed` (and its packaged form
`FrameworkRoot.finiteVCIdeal_closed`): the statement that the finite-VC ideal — the boundary value
of the `Inv` coordinate — is **closed under all of the framework's structure-building moves at
once** (pullback, exclusive-or relabelling, union, intersection, Boolean combination, and bidual).
No existing file states this conjunction; each proves one conjunct in isolation. Assembling them
into a single closure statement is the new lemma, and its proof is exactly the composition of the
anchors. This is the honest `experiment` content of the module; everything else is `describe`.

## Map to anchors

| quartet slot | re-exported anchor(s) | source file |
|---|---|---|
| GR1 generator | `shatters_mono`, `shatters_of_subset`, `growthFunction_ge_two_pow_of_shatters` | `Monotone`, `VCFinite`, `ShatterCount` |
| Coh (GR4) | `bridge_round_trip` | `FLT_Proofs.Bridge` |
| Inv (GR3) | `vcDim_fundamental_theorem` | `FundamentalTheorem` |
| Pl (GR5) | `pullback_id`, `pullback_pullback`, `vcDim_pullback_le`, `vcDim_pullback_equiv`, `vcDim_le_biDual`, `pullback_biDual_eq`, `vcDim_dualClass_le` | `Pullback`, `PullbackEquiv`, `Dual`, `DualBound` |
| Comp (GR6) | `vcDim_union_le`, `vcDim_inter_le_min`, `growthFunction_booleanComb_le_prod`, `hasPolyDegree_booleanComb`, `vcDim_modular_on_chain`, `vcDim_not_polymatroid_rank` | `UnionTight`, `Monotone`, `GrowthMul`, `VCDensity`, `OpenRouteR1`, `MatroidStructure` |
-/

open Filter

universe u v w

variable {X : Type u} {Y : Type v} {Z : Type w}

/-! ## GR1 — the shattering generator

`Shatters X C S` is the single primitive from which the whole theory grows. The structure axis asks
*where* it holds, the expressivity axis asks *how rich* its support is, and the capacity axis asks
*how fast* its complement grows under sampling. The three monotonicities below are the basic moves
of the generator; the exponential lower bound is its operational shadow (a shattered sample forces
the growth function up to `2 ^ m`).

The declarations in this section are **re-exports**, not new theorems. -/

/-- **GR1 — shattering is monotone in the class** (re-export of `shatters_mono`). A labelling realized
inside `C` is realized inside any larger class. -/
theorem framework_shatters_mono {C D : ConceptClass X Bool} (h : C ⊆ D) {S : Finset X}
    (hS : Shatters X C S) : Shatters X D S :=
  shatters_mono h hS

/-- **GR1 — shattering is monotone in the sample** (re-export of `shatters_of_subset`). A subset of a
shattered sample is shattered. -/
theorem framework_shatters_of_subset {C : ConceptClass X Bool} {S T : Finset X}
    (hS : Shatters X C S) (hTS : T ⊆ S) : Shatters X C T :=
  shatters_of_subset hS hTS

/-- **GR1 — the operational shadow of the generator** (re-export of
`growthFunction_ge_two_pow_of_shatters`). A shattered sample of size `m` forces the growth function at
`m` up to `2 ^ m`; this is the half of the capacity dichotomy that produces the exponential lower
bound. -/
theorem framework_growth_ge_two_pow_of_shatters {C : ConceptClass X Bool} {S : Finset X}
    (h : Shatters X C S) : 2 ^ S.card ≤ GrowthFunction X C S.card :=
  growthFunction_ge_two_pow_of_shatters h

/-! ## Coh (GR4) — the carrier identity (concept class ≅ set family)

The coherence backbone: a concept class over `Bool` *is* a set family. This is the typed statement
that licenses moving a theorem between the three charts — it is why structure, expressivity, and
capacity are charts on the *same* object rather than three different subjects.

Re-export, not a new theorem. -/

/-- **Coh (GR4) — the carrier identity** (re-export of `bridge_round_trip`). The round trip
`ConceptClass X Bool → Set (Set X) → ConceptClass X Bool` is the identity: a Bool-valued concept is
determined by its level set, so a concept class and its set family carry the same information. -/
theorem framework_carrier_identity (C : ConceptClass X Bool) :
    setFamilyToConceptClass X (conceptClassToSetFamily X C) = C :=
  bridge_round_trip X C

/-! ## Inv (GR3) — the finite-vs-`⊤` invariant

The only genuinely chart-independent invariant is the dichotomy `VCDim C < ⊤` versus `VCDim C = ⊤`.
The integer value and the rate constant are chart-dependent; the *jump to `⊤`* is chart-free, and it
is precisely the fundamental theorem of statistical learning. The `WithTop ℕ` codomain is the carrier
of this invariant.

Re-export, not a new theorem. -/

/-- **Inv (GR3) — the invariant is the fundamental theorem** (re-export of
`vcDim_fundamental_theorem`). For a measurable concept class, the boundary value of the `Inv`
coordinate — finite VC dimension — coincides with PAC learnability and with eventually-polynomial
growth. The finite-vs-`⊤` jump is the chart-free content. -/
theorem framework_invariant_fundamental_theorem [MeasurableSpace X] [MeasurableSingletonClass X]
    (C : ConceptClass X Bool) [MeasurableConceptClass X C] :
    (VCDim X C < ⊤ ↔ PACLearnable X C) ∧
      (VCDim X C < ⊤ ↔
        ∃ (K : ℝ) (d : ℕ), ∀ᶠ m : ℕ in atTop, (GrowthFunction X C m : ℝ) ≤ K * (m : ℝ) ^ d) :=
  vcDim_fundamental_theorem C

/-! ## Pl (GR5) — the duality / pullback geometry

Pullback is a contravariant functor on concept classes (`pullback_id`, `pullback_pullback`), under
which VC dimension is monotone-decreasing (`vcDim_pullback_le`) and relabelling-invariant
(`vcDim_pullback_equiv`). The dual swaps points and concepts; it is an involution *up to bidual*
(`pullback_biDual_eq`, `vcDim_le_biDual`) with a controlled exponential blow-up
(`vcDim_dualClass_le`, Assouad). This is the plausibility-of-structure grammar: the arrows are all
proven; only the *named category* is left open (a conjecture in the synthesis, not banked here).

All declarations in this section are re-exports, not new theorems. -/

/-- **Pl (GR5) — pullback is functorial: identity law** (re-export of `pullback_id`). -/
theorem framework_pullback_id (C : ConceptClass X Bool) : pullback (id : X → X) C = C :=
  pullback_id C

/-- **Pl (GR5) — pullback is functorial: composition law** (re-export of `pullback_pullback`).
Pulling back along `g` then `f` is pulling back along `f ∘ g` — contravariance. -/
theorem framework_pullback_pullback (f : Y → X) (g : Z → Y) (C : ConceptClass X Bool) :
    pullback g (pullback f C) = pullback (f ∘ g) C :=
  pullback_pullback f g C

/-- **Pl (GR5) — VC dimension is monotone-decreasing under pullback** (re-export of
`vcDim_pullback_le`). This is the contravariant functoriality of the `Inv` coordinate. -/
theorem framework_vcDim_pullback_le (f : Y → X) (C : ConceptClass X Bool) :
    VCDim Y (pullback f C) ≤ VCDim X C :=
  vcDim_pullback_le f C

/-- **Pl (GR5) — VC dimension is relabelling-invariant** (re-export of `vcDim_pullback_equiv`). A
bijection of the domain preserves the VC dimension: capacity depends only on the incidence between
concepts and points, not on the names of either. -/
theorem framework_vcDim_pullback_equiv (e : Y ≃ X) (C : ConceptClass X Bool) :
    VCDim Y (pullback (e : Y → X) C) = VCDim X C :=
  vcDim_pullback_equiv e C

/-- **Pl (GR5) — the bidual recovers the primal** (re-export of `pullback_biDual_eq`). Pulling the
bidual back along the evaluation embedding reproduces `C` exactly: the (co)unit of the
point↔concept duality. -/
theorem framework_pullback_biDual_eq (C : ConceptClass X Bool) :
    pullback (fun x => (⟨evalConcept C x, evalConcept_mem C x⟩ : ↥(dualClass C)))
      (dualClass (dualClass C)) = C :=
  pullback_biDual_eq C

/-- **Pl (GR5) — the bidual lower bound** (re-export of `vcDim_le_biDual`). The VC dimension of a class
is at most that of its bidual; the dual is an involution only up to this inequality. -/
theorem framework_vcDim_le_biDual (C : ConceptClass X Bool) :
    VCDim X C ≤ VCDim ↥(dualClass C) (dualClass (dualClass C)) :=
  vcDim_le_biDual C

/-- **Pl (GR5) — Assouad's dual bound** (re-export of `vcDim_dualClass_le`). Dualizing blows the VC
dimension up by at most `2 ^ (d + 1) − 1`: the exponential price of the point↔concept swap. -/
theorem framework_vcDim_dualClass_le {C : ConceptClass X Bool} {d : ℕ}
    (hd : VCDim X C ≤ (d : WithTop ℕ)) :
    VCDim ↥C (dualClass C) ≤ ((2 ^ (d + 1) - 1 : ℕ) : WithTop ℕ) :=
  vcDim_dualClass_le hd

/-! ## Comp (GR6) — the composition calculus

Composition (union, intersection, Boolean combination) is the amplification axis. The upper bounds
are proven and shared; the *sharp two-class bound* is `VCDim C + VCDim D + 1` (`vcDim_union_le`); but
the calculus has a **forbidden law**: additivity. The matroid Pl-kill `vcDim_not_polymatroid_rank`
shows VC dimension is monotone and normalized yet *not* submodular, so it is not a polymatroid rank.
The subadditive surrogate lives one scale down, at VC *density* (`hasPolyDegree_booleanComb`).

All declarations in this section are re-exports, not new theorems. -/

/-- **Comp (GR6) — the sharp two-class union bound** (re-export of `vcDim_union_le`).
`VCDim (C ∪ D) ≤ dC + dD + 1`, and the constant is sharp. -/
theorem framework_vcDim_union_le {C D : ConceptClass X Bool} {dC dD : ℕ}
    (hC : VCDim X C ≤ (dC : WithTop ℕ)) (hD : VCDim X D ≤ (dD : WithTop ℕ)) :
    VCDim X (C ∪ D) ≤ ((dC + dD + 1 : ℕ) : WithTop ℕ) :=
  vcDim_union_le hC hD

/-- **Comp (GR6) — the intersection bound** (re-export of `vcDim_inter_le_min`). -/
theorem framework_vcDim_inter_le_min (C D : ConceptClass X Bool) :
    VCDim X (C ∩ D) ≤ min (VCDim X C) (VCDim X D) :=
  vcDim_inter_le_min C D

/-- **Comp (GR6) — the growth function is sub-multiplicative under Boolean combination** (re-export of
`growthFunction_booleanComb_le_prod`). The combinatorial root of the density subadditivity. -/
theorem framework_growth_booleanComb_le_prod {k : ℕ} (φ : (Fin k → Bool) → Bool)
    (C : Fin k → ConceptClass X Bool) (m : ℕ) :
    GrowthFunction X (booleanComb φ C) m ≤ ∏ i, GrowthFunction X (C i) m :=
  growthFunction_booleanComb_le_prod φ C m

/-- **Comp (GR6) — VC density *is* subadditive** (re-export of `hasPolyDegree_booleanComb`). The
subadditive surrogate one scale below dimension: a Boolean combination of classes of degrees `r i`
has degree `∑ r i`. This is exactly what dimension forbids and density permits. -/
theorem framework_density_subadditive {k : ℕ} (φ : (Fin k → Bool) → Bool)
    (C : Fin k → ConceptClass X Bool) (r : Fin k → ℝ) (h : ∀ i, HasPolyDegree (C i) (r i)) :
    HasPolyDegree (booleanComb φ C) (∑ i, r i) :=
  hasPolyDegree_booleanComb φ C r h

/-- **Comp (GR6) — modularity on chains** (re-export of `vcDim_modular_on_chain`). On a chain the
submodular inequality is an equality; submodularity can only fail off chains. -/
theorem framework_vcDim_modular_on_chain {C D : ConceptClass X Bool} (h : C ⊆ D) :
    VCDim X (C ∪ D) + VCDim X (C ∩ D) = VCDim X C + VCDim X D :=
  vcDim_modular_on_chain h

/-- **Comp (GR6) — the forbidden law (matroid Pl-kill)** (re-export of `vcDim_not_polymatroid_rank`).
VC dimension is monotone and normalized, yet not submodular on the concept-class lattice, hence not a
polymatroid rank. The sharp negative content of the composition calculus. -/
theorem framework_not_polymatroid_rank :
    (∀ {X : Type u} {C D : ConceptClass X Bool}, C ⊆ D → VCDim X C ≤ VCDim X D)
      ∧ (∀ {X : Type u}, VCDim X (∅ : ConceptClass X Bool) = ⊥)
      ∧ ¬ ∀ X : Type, VCDimSubmodular X :=
  vcDim_not_polymatroid_rank

/-! ## The SEVEN GM actions — the uniform moves on the one object

The framework verbs. Each operates uniformly across the three charts; the catalogue records the
*carrier declaration* and the *uniform law* of each, drawn from the re-exports above and from the
wider development.

* **GM1 — Restrict / pullback** (contravariant reindex). Carrier: `pullback`. Uniform law:
  monotone-decreasing on capacity, invariant under equivalence (`framework_vcDim_pullback_le`,
  `framework_vcDim_pullback_equiv`). This is the generator of the finitization family.
* **GM2 — Dualize** (point↔concept swap). Carrier: `dualClass`. Uniform law: controlled exponential
  blow-up, recovery up to bidual (`framework_vcDim_dualClass_le`, `framework_pullback_biDual_eq`,
  `framework_vcDim_le_biDual`).
* **GM3 — Symmetrize / sign-flip** (exclusive-or shift). Carrier: `xorShift`. Uniform law: involutive
  and shattering-preserving (`shatters_xorShift`, `xorShift_xorShift`, `vcDim_xorShift`).
* **GM4 — Compose / combine** (Boolean lattice). Carrier: `booleanComb` / `unionClass` / `interClass`.
  Uniform law: closure of finiteness with explicit bounds, additivity forbidden
  (`framework_vcDim_union_le`, `framework_vcDim_inter_le_min`, `framework_not_polymatroid_rank`).
* **GM5 — Relabel** (symmetry action). Carrier: `pullback` along an `Equiv`. Uniform law: capacity is
  exactly invariant under relabelling (`framework_vcDim_pullback_equiv`, `shatters_xorShift`).
* **GM6 — Shatter-witness** (adversary extraction). Carrier: `Shatters` unfolded to a realizing
  labelling. Uniform law: shattering yields a certificate / lower bound
  (`framework_growth_ge_two_pow_of_shatters`). The expressivity→capacity arrow.
* **GM7 — Scale-flow / discretize** (`ε ↓ 0`). Carrier: covering nets / Dudley chaining (in the
  real-valued and TLT strata). Uniform law: the continuous analogue of GM1; capacity is the limit
  invariant.

**Coupling note.** `GM1 ≡ GM3 ≡ GM7` are the three resolutions of one move — the finitization verb
`Fin↓` ("replace the infinite object by a finite combinatorial trace at a resolution parameter"):
GM1 resolves by sample size, GM3 by sign pattern, GM7 by scale. `GM2` and `GM5` are the two
involutions of the `Pl` geometry; `GM4` is the binary operation of `Comp`; `GM6` is the
realizing/forgetful functor that turns the generator `Shatters` into a witness.

The carrier declarations are listed here as documentation; the laws are the re-exports above. The
unification *itself* (that these are one action-set, that `Fin↓` is one verb) is the synthesis's
conjecture and is **not** banked as a theorem — only the per-action laws are kernel-verified. -/

/-! ## The genuinely-new bundling lemma — closure of the `Inv` ideal under the framework moves

The finite-VC ideal `{C | VCDim X C < ⊤}` is the boundary value of the `Inv` coordinate: it is the
PAC-learnable side of the fundamental-theorem dichotomy. Each constituent file proves, in isolation,
that *one* framework move preserves this ideal. The lemma below is the new content: it assembles them
into a single statement that the ideal is closed under **all** the structure-building moves at once —
pullback (GM1), exclusive-or relabelling (GM3/GM5), union and intersection and Boolean combination
(GM4 / Comp), and bidual (GM2). The proof is the composition of the anchors; the conjunction is the
new theorem (no existing file states it). -/

/-- **Closure of the finite-VC ideal under the framework actions** (new). If `C` and the family
`Cs i` all have finite VC dimension, then so does every class obtained from them by the
framework's structure-building moves: the pullback `pullback f C` (GM1), the exclusive-or shift
`xorShift a C` (GM3/GM5), the union `C ∪ D`, the intersection `C ∩ D`, and any Boolean combination
`booleanComb φ Cs` (GM4 / Comp), and the bidual `dualClass (dualClass C)` (GM2).

This is the typed form of the slogan "the finite-VC ideal is a *closed* subobject under the action
grammar": it is the conjunction the matroid Pl-kill leaves intact (finiteness is preserved even
though the *value* is not additive). Each conjunct is a known anchor; the bundling is new. -/
theorem vcDim_finite_ideal_closed {C D : ConceptClass X Bool} {k : ℕ}
    (Cs : Fin k → ConceptClass X Bool) (φ : (Fin k → Bool) → Bool)
    (hC : VCDim X C < ⊤) (hD : VCDim X D < ⊤) (hCs : ∀ i, VCDim X (Cs i) < ⊤)
    (f : Y → X) (a : X → Bool) :
    VCDim Y (pullback f C) < ⊤
      ∧ VCDim X (xorShift a C) < ⊤
      ∧ VCDim X (C ∪ D) < ⊤
      ∧ VCDim X (C ∩ D) < ⊤
      ∧ VCDim X (booleanComb φ Cs) < ⊤
      ∧ VCDim ↥C (dualClass C) < ⊤ := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_⟩
  · -- GM1: pullback only decreases the VC dimension.
    exact lt_of_le_of_lt (vcDim_pullback_le f C) hC
  · -- GM3 / GM5: exclusive-or relabelling preserves it exactly.
    rwa [vcDim_xorShift]
  · -- GM4 / Comp: union of two finite-VC classes is finite-VC.
    exact vcDim_union_finite hC hD
  · -- GM4 / Comp: intersection is bounded by the minimum, hence finite.
    exact lt_of_le_of_lt (vcDim_inter_le_min C D) (lt_of_le_of_lt (min_le_left _ _) hC)
  · -- GM4 / Comp: any Boolean combination of finite-VC classes is finite-VC.
    exact vcDim_booleanComb_finite φ Cs hCs
  · -- GM2: dualizing a finite-VC class stays finite-VC (Assouad).
    exact vcDim_dualClass_lt_top hC

/-! ## The framework-root bundle

A small record packaging a concept class together with the data needed to *talk about* its position
in the framework: the class itself and the boundary value of its `Inv` coordinate (finite VC
dimension). This is organizing scaffolding — a place to hang the measurement coordinates — not a
theorem. Its one method, `dualClosed`, is the bundle-level shadow of `vcDim_finite_ideal_closed`'s
bidual conjunct (GM2): a finite-VC root has a finite-VC dual, so the bundle is closed under
dualization. -/

/-- A **framework root**: a concept class carried together with a witness that it lies in the
finite-VC ideal (the PAC-learnable side of the `Inv` dichotomy). The structure is an organizing
record, not a theorem; it bundles the object with the boundary value of its capacity coordinate. -/
structure FrameworkRoot (X : Type u) where
  /-- The underlying concept class — the one object of the framework. -/
  carrier : ConceptClass X Bool
  /-- Witness that the `Inv` coordinate is on its finite side: `VCDim < ⊤`. -/
  finiteVC : VCDim X carrier < ⊤

namespace FrameworkRoot

/-- **The framework root is closed under dualization** (GM2 at the bundle level). The dual of a
finite-VC root is again a finite-VC root, by `vcDim_dualClass_lt_top`. This packages the bidual
conjunct of `vcDim_finite_ideal_closed` as a map on roots. -/
noncomputable def dualClosed (R : FrameworkRoot X) : FrameworkRoot ↥R.carrier where
  carrier := dualClass R.carrier
  finiteVC := vcDim_dualClass_lt_top R.finiteVC

end FrameworkRoot
